// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.curre5ntPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy8Iq7vO_Qy3SEuaqrblVuSSyf5NuQFN8',
    appId: '1:128582067514:web:03ef16d52551005ba79c03',
    messagingSenderId: '128582067514',
    projectId: 'blood-bank-5fdec',
    authDomain: 'blood-bank-5fdec.firebaseapp.com',
    storageBucket: 'blood-bank-5fdec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2jHmaEgsv8SFwfTYybDD-tbt5Nn6yWYg',
    appId: '1:128582067514:android:44647b2c0f657785a79c03',
    messagingSenderId: '128582067514',
    projectId: 'blood-bank-5fdec',
    storageBucket: 'blood-bank-5fdec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC7J8yy_KKGDdeN3y30EnY-p90tcqkUXQ',
    appId: '1:128582067514:ios:814ebd11bc6f2909a79c03',
    messagingSenderId: '128582067514',
    projectId: 'blood-bank-5fdec',
    storageBucket: 'blood-bank-5fdec.appspot.com',
    iosClientId:
        '128582067514-qb16ec18bs13afefrio1jrmekmj69m6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC7J8yy_KKGDdeN3y30EnY-p90tcqkUXQ',
    appId: '1:128582067514:ios:74d2d0a7d69324a0a79c03',
    messagingSenderId: '128582067514',
    projectId: 'blood-bank-5fdec',
    storageBucket: 'blood-bank-5fdec.appspot.com',
    iosClientId:
        '128582067514-101anc9ur3bui04sl93feqbdcc7gbhes.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodBank.RunnerTests',
  );
}
